name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Execute a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate Snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: lua-rib
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check if SVG exists
        run: ls dist/github-contribution-grid-snake.svg

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
